### ISSUE TITLE
Pycharm imports fix

### ISSUE THREAD

**Issue by silentninja** [Khan/slicker#25]
You can change the way pycharm auto imports by going to Settings > Editor > General > Auto Import and changing the preferred style. But this tool is nice for writing automation scripts!

**Comment by benjaminjkraft** [comment]
Yep!  That may be good enough for some users.  Unfortunately, our import style makes two requirements which PyCharm doesn't seem to support: first, we only import modules, not individual symbols from a module (e.g. `from graphene import types` is fine, but not `from graphene import ObjectType`); and second, we never put multiple imports on one line (e.g. `from foo import bar, baz`).
